//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class telefono
    {
        public string cedula { get; set; }
        [Display(Name = "Telefono:")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "El teléfono solo puede estar compuesto por números")]
        public string telefono1 { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
